# backend/alembic/versions/0001_initial_schema.py
# This is your first migration — it creates all existing tables from scratch.
# Generated by running: alembic revision --autogenerate -m "initial schema"
# Then EDITED to be clean and explicit. Use this as your baseline.
#
# After applying, future schema changes go in new revision files —
# never hand-edit this file again.

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "incidents",
        sa.Column("id",               sa.Integer(),  primary_key=True, index=True),
        sa.Column("title",            sa.String(),   nullable=False),
        sa.Column("severity",         sa.String(),   nullable=False),
        sa.Column("status",           sa.String(),   nullable=False, server_default="Open"),
        sa.Column("description",      sa.String(),   nullable=False),
        sa.Column("remediation",      sa.String(),   nullable=False),
        sa.Column("confidence",       sa.Integer(),  nullable=False),
        sa.Column("source",           sa.String(),   nullable=True),
        sa.Column("pipeline_id",      sa.String(),   nullable=True),
        sa.Column("gitlab_issue_url", sa.String(),   nullable=True),
        sa.Column("autofix_mr_url",   sa.String(),   nullable=True),
        sa.Column("created_at",       sa.DateTime(), nullable=False),
        sa.Column("updated_at",       sa.DateTime(), nullable=False),
    )

    op.create_table(
        "deployments",
        sa.Column("id",         sa.Integer(), primary_key=True, index=True),
        sa.Column("workflow",   sa.String(),  nullable=False),
        sa.Column("branch",     sa.String(),  nullable=False),
        sa.Column("commit",     sa.String(),  nullable=False),
        sa.Column("actor",      sa.String(),  nullable=False),
        sa.Column("conclusion", sa.String(),  nullable=True),
        sa.Column("run_number", sa.Integer(), nullable=True),
        sa.Column("url",        sa.String(),  nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
    )

    op.create_table(
        "monitored_projects",
        sa.Column("id",                sa.Integer(), primary_key=True, index=True),
        sa.Column("gitlab_project_id", sa.String(),  nullable=False, unique=True, index=True),
        sa.Column("name",              sa.String(),  nullable=False),
        sa.Column("description",       sa.String(),  nullable=True),
        sa.Column("active",            sa.Boolean(), nullable=False, server_default="1"),
        sa.Column("webhook_secret",    sa.String(),  nullable=True),
        sa.Column("created_at",        sa.DateTime(), nullable=False),
    )

    op.create_table(
        "audit_logs",
        sa.Column("id",          sa.Integer(), primary_key=True, index=True),
        sa.Column("incident_id", sa.Integer(), sa.ForeignKey("incidents.id"), nullable=False),
        sa.Column("action",      sa.String(),  nullable=False),
        sa.Column("detail",      sa.String(),  nullable=True),
        sa.Column("actor",       sa.String(),  nullable=True, server_default="system"),
        sa.Column("created_at",  sa.DateTime(), nullable=False),
    )


def downgrade() -> None:
    op.drop_table("audit_logs")
    op.drop_table("monitored_projects")
    op.drop_table("deployments")
    op.drop_table("incidents")
